/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/Sidebar/AboutSection.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    ButtonWithIcon: typeof import('./src/components/MenuItems/ButtonWithIcon.vue')['default']
    CentralCanvas: typeof import('./src/components/Main/CentralCanvas.vue')['default']
    EditButtons: typeof import('./src/components/Sidebar/EditButtons.vue')['default']
    FeatureSelector: typeof import('./src/components/Sidebar/FeatureSelector.vue')['default']
    LoadSaveActions: typeof import('./src/components/Sidebar/LoadSaveActions.vue')['default']
    ModelSelector: typeof import('./src/components/Sidebar/ModelSelector.vue')['default']
    SidebarContainer: typeof import('./src/components/Main/SidebarContainer.vue')['default']
    ThumbnailContainer: typeof import('./src/components/ThumbnailContainer.vue')['default']
    ThumbnailGallery: typeof import('./src/components/Main/ThumbnailGallery.vue')['default']
    ViewOptions: typeof import('./src/components/Sidebar/ViewOptions.vue')['default']
  }
}
